# -*- coding: utf-8 -*-
"""RestMex2026-Ollama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XuLJrKsauHLjFRZLXKXzvPeG3C2KNxly
"""

#!/usr/bin/env python3
"""
REST-MEX 2026: Synthetic Text Generator for Mexican Magical Towns
==================================================================
Genera 3,000 reseñas turísticas sintéticas en español usando Ollama
(local o web API) para evaluación indirecta de análisis de sentimiento.

Autor: PhD Strategy Team
Fecha: 2026
Competencia: IberLef 2026 - REST-MEX
"""

import os
import sys
import json
import time
import random
import logging
import argparse
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Union

import os, json, re, zipfile, time, argparse
import numpy as np
from pathlib import Path
from collections import Counter, defaultdict
from typing import Optional

import requests
import pandas as pd
import numpy as np
import requests
from tqdm import tqdm
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, classification_report
from sklearn.model_selection import train_test_split

# ============================================================================
# CONFIGURACIÓN GLOBAL
# ============================================================================

# Constants del reto REST-MEX 2026
RESTMEX_CONFIG = {
    'TARGET_REVIEWS': 3000,
    'POLARITY_CLASSES': [1, 2, 3, 4, 5],
    'POLARITY_LABELS': {
        1: 'Muy negativo',
        2: 'Negativo',
        3: 'Neutral',
        4: 'Positivo',
        5: 'Muy positivo'
    },
    'REQUIRED_COLUMNS': ['opinion', 'polarity', 'source'],
    'MIN_REVIEW_LENGTH': 20,
    'MAX_REVIEW_LENGTH': 200,
    'EMBEDDING_MODEL': 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
    'SIMILARITY_THRESHOLD': 0.85,  # Para filtrar duplicados semánticos
}

# Configuración de logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('restmex_generation.log', encoding='utf-8'),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

# ============================================================================
# CLIENTE OLLAMA (Local y Web API)
# ============================================================================

class OllamaClient:
    """
    Cliente flexible para Ollama: soporta modo local y web API remota.
    """

    def __init__(
        self,
        model: str = "llama3",
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        timeout: int = 90,
        max_retries: int = 15,
        mode: str = "local"
    ):
        self.model = model
        self.mode = mode
        
        # Configurar URL según el modo
        if base_url:
            self.base_url = base_url
        elif mode == "web":
            # Para modo web, usar un servidor remoto de Ollama si está configurado
            self.base_url = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
        else:
            self.base_url = os.getenv("OLLAMA_API_URL", "http://localhost:11434")
        
        self.api_key = api_key or os.getenv("OLLAMA_API_KEY")
        self.timeout = timeout
        self.max_retries = max_retries
        self.session = requests.Session()

        if self.api_key:
            self.session.headers.update({"Authorization": f"Bearer {self.api_key}"})

        logger.info(f"🦙 OllamaClient inicializado: model={model}, url={self.base_url}, mode={mode}")

    def generate(
        self,
        prompt: str,
        temperature: float = 0.5,
        max_tokens: int = 150,
        top_p: float = 0.9,
        min_length: int = 10
    ) -> Optional[str]:
        """
        Genera texto usando Ollama con reintentos automáticos.
        """
        # Construir la URL correcta según el endpoint
        generate_url = f"{self.base_url}/api/generate"
        
        for attempt in range(self.max_retries):
            try:
                payload = {
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": temperature,
                        "top_p": top_p,
                        "num_predict": max_tokens,
                        "repeat_penalty": 1.1,  # Reduce repetición
                        "stop": []  # No detener prematuramente
                    }
                }
                
                response = self.session.post(
                    generate_url,
                    json=payload,
                    timeout=self.timeout
                )

                if response.status_code == 200:
                    result = response.json()
                    text = result.get('response', '').strip()

                    # Validación básica de calidad
                    if text and len(text) >= min_length:
                        return text
                    else:
                        logger.warning(f"⚠️ Respuesta muy corta ({len(text)} chars): '{text[:50]}...'")
                        # Si es muy corto, no reintentar inmediatamente, continuar al siguiente intento
                else:
                    logger.error(f"❌ Error HTTP {response.status_code}: {response.text[:200]}")

            except requests.exceptions.ConnectionError:
                logger.error(f"❌ ConnectionError (intento {attempt + 1}/{self.max_retries})")
            except requests.exceptions.Timeout:
                logger.error(f"❌ Timeout (intento {attempt + 1}/{self.max_retries})")
            except Exception as e:
                logger.error(f"❌ Error inesperado (intento {attempt + 1}): {e}")

            # Backoff exponencial entre reintentos
            if attempt < self.max_retries - 1:
                wait_time = min(2 * (2 ** attempt), 16)  # Máximo 16 segundos
                logger.info(f"⏳ Esperando {wait_time}s antes de reintentar...")
                time.sleep(wait_time)
        
        logger.error(f"❌ Falló después de {self.max_retries} intentos")
        return None
    
    def parse_json(self, raw: str) -> Optional[dict]:
        raw = raw.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"```\s*$", "", raw).strip()
        m   = re.search(r"\{[\s\S]*\}", raw)
        if m:
            raw = m.group(0)
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return None
    
    def complete(self, system: str, user: str) -> Optional[str]:
        """
        Completa un chat usando el formato de mensajes de Ollama.
        """
        chat_url = f"{self.base_url}/api/chat"
        
        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        
        payload = {
            "model": self.model, 
            "stream": False,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "options": {"temperature": 0.7, "num_predict": 600},
        }
        
        try:
            r = self.session.post(chat_url, headers=headers, json=payload, timeout=self.timeout)
            r.raise_for_status()
            return r.json()["message"]["content"]
        except requests.ConnectionError:
            logger.error(f"❌ [Ollama] Cannot connect to {chat_url}")
        except requests.HTTPError as e:
            logger.error(f"❌ [Ollama {e.response.status_code}] {e.response.text[:150]}")
        except (KeyError, ValueError) as e:
            logger.error(f"❌ [Ollama parse] {e}")
        return None


    def test_connection(self) -> bool:
        """Prueba rápida de conectividad con Ollama."""
        try:
            # Usar endpoint de tags para verificar conexión (más confiable)
            tags_url = f"{self.base_url}/api/tags"
            response = self.session.get(tags_url, timeout=5)
            
            if response.status_code == 200:
                models = response.json().get('models', [])
                model_names = [m.get('name', '') for m in models]
                
                # Verificar que el modelo especificado existe
                if any(self.model in name for name in model_names):
                    logger.info(f"✅ Conexión a Ollama verificada exitosamente")
                    logger.info(f"✅ Modelo '{self.model}' encontrado")
                    return True
                else:
                    logger.warning(f"⚠️ Modelo '{self.model}' no encontrado")
                    logger.info(f"📋 Modelos disponibles: {', '.join(model_names[:5])}")
                    # Aún así retornar True si la conexión funciona
                    return True
            else:
                logger.error(f"❌ Error HTTP {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"❌ Falló la prueba de conexión: {e}")
            return False

    def close(self):
        self.session.close()

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()





# ============================================================================
# ANÁLISIS DE DATOS REALES
# ============================================================================

class DataAnalyzer:
    """
    Analiza los datos reales proporcionados para guiar la generación sintética.
    """

    def __init__(self, embedding_model_name: str = RESTMEX_CONFIG['EMBEDDING_MODEL']):
        logger.info(f"🔍 Cargando modelo de embeddings: {embedding_model_name}")
        self.embedding_model = SentenceTransformer(embedding_model_name)
        self.df_real = None
        self.distribution = {}

    def load_data(self, filepath: str) -> pd.DataFrame:
        """Carga y valida el CSV de datos reales."""
        logger.info(f"📂 Cargando datos desde: {filepath}")

        df = pd.read_csv(filepath)

        # Normalizar nombres de columnas
        df.columns = df.columns.str.lower().str.strip()

        # Validar columnas requeridas
        required = ['review', 'polarity']
        missing = [col for col in required if col not in df.columns]

        if missing:
            raise ValueError(f"❌ Columnas faltantes en el archivo: {missing}")

        # Limpieza básica
        df = df.dropna(subset=['review', 'polarity'])
        df['review'] = df['review'].astype(str).str.strip()
        df['polarity'] = df['polarity'].astype(int)

        # Filtrar polaridades válidas
        df = df[df['polarity'].isin(RESTMEX_CONFIG['POLARITY_CLASSES'])]

        self.df_real = df
        logger.info(f"✅ Datos cargados: {len(df)} reseñas válidas")

        return df

    def analyze_distribution(self) -> Dict[int, float]:
        """Analiza la distribución de clases de sentimiento."""
        if self.df_real is None:
            raise ValueError("Primero carga los datos con load_data()")

        counts = self.df_real['polarity'].value_counts().sort_index()
        total = len(self.df_real)

        self.distribution = {
            polarity: {
                'count': int(counts.get(polarity, 0)),
                'percentage': round(counts.get(polarity, 0) / total * 100, 2)
            }
            for polarity in RESTMEX_CONFIG['POLARITY_CLASSES']
        }

        logger.info("📊 Distribución de polaridades en datos reales:")
        for p, info in self.distribution.items():
            bar = "█" * int(info['percentage'] / 5)
            logger.info(f"  {p} ({RESTMEX_CONFIG['POLARITY_LABELS'][p]}): "
                       f"{info['count']} ({info['percentage']}%) {bar}")

        return self.distribution

    def extract_style_features(self, n_samples: int = 100) -> Dict:
        """Extrae características de estilo de las reseñas reales."""
        if self.df_real is None:
            raise ValueError("Primero carga los datos con load_data()")

        samples = self.df_real.sample(n=min(n_samples, len(self.df_real)), random_state=42)

        # Longitud promedio por polaridad
        length_stats = samples.groupby('polarity')['review'].apply(
            lambda x: {'mean': x.str.len().mean(), 'std': x.str.len().std()}
        ).to_dict()

        # Palabras más frecuentes (top 20)
        from collections import Counter
        import re

        words = []
        for text in samples['review']:
            # Tokenización simple en español
            tokens = re.findall(r'\b[a-zA-ZáéíóúñüÁÉÍÓÚÑÜ]{3,}\b', text.lower())
            words.extend(tokens)

        word_freq = Counter(words).most_common(20)

        return {
            'length_by_polarity': length_stats,
            'top_words': word_freq,
            'avg_length': samples['review'].str.len().mean()
        }

    def compute_embeddings(self, texts: List[str], batch_size: int = 32) -> np.ndarray:
        """Computa embeddings para un conjunto de textos."""
        return self.embedding_model.encode(
            texts,
            batch_size=batch_size,
            show_progress_bar=True,
            convert_to_numpy=True
        )


# ============================================================================
# GENERADOR DE RESEÑAS SINTÉTICAS
# ============================================================================

class SyntheticReviewGenerator:
    """
    Genera reseñas sintéticas usando Ollama con control de polaridad y estilo.
    """

    # Aspectos turísticos comunes en Pueblos Mágicos
    ASPECTS = [
        "gastronomía y comida típica",
        "hoteles y alojamiento",
        "seguridad y tranquilidad",
        "precios y relación calidad-precio",
        "transporte y accesibilidad",
        "atractivos turísticos y paisajes",
        "atención del personal y servicio",
        "limpieza y mantenimiento",
        "cultura local y tradiciones",
        "ambiente y experiencia general"
    ]

    # Pueblos Mágicos representativos
    TOWNS = [
        "Tepoztlán", "San Cristóbal de las Casas", "Valle de Bravo",
        "Pátzcuaro", "Taxco", "Real de Catorce", "San Miguel de Allende",
        "Tequila", "Magical Town", "Pueblo Mágico"
    ]

    # Descripciones de polaridad para prompts
    POLARITY_PROMPTS = {
        1: "Muy negativa: enfócate en problemas graves como inseguridad, suciedad extrema, estafas, mala atención. El turista está muy decepcionado y no recomendaría el lugar.",
        2: "Negativa: experiencia decepcionante, precios altos para lo ofrecido, atención deficiente, expectativas no cumplidas. Aspectos negativos predominan.",
        3: "Neutral: mezcla equilibrada de aspectos positivos y negativos. Ni excelente ni terrible. Experiencia promedio sin emociones fuertes.",
        4: "Positiva: disfrutaste la visita, buenos aspectos predominan, experiencia agradable. Quizás algún detalle menor mejorable pero en general satisfactorio.",
        5: "Muy positiva: experiencia increíble, mágica, inolvidable. Definitivamente regresarías y lo recomendarías. Elogios a la cultura, gente, paisajes y gastronomía."
    }

    def __init__(
        self,
        ollama_client: OllamaClient,
        data_analyzer: DataAnalyzer,
        target_per_class: int = 600  # 600 × 5 clases = 3,000
    ):
        self.ollama = ollama_client
        self.analyzer = data_analyzer
        self.target_per_class = target_per_class
        self.generated_reviews = []
        self.generation_log = []

    def _build_prompt(self, polarity: int, aspect: str, town: str, style_features: Dict) -> str:
        """Construye un prompt optimizado para generación de reseñas."""

        # Obtener características de estilo para guiar la generación
        avg_length = style_features.get('avg_length', 100)
        min_length = max(60, int(avg_length - 20))
        max_length = min(200, int(avg_length + 40))

        # Ejemplos mejorados según polaridad
        ejemplos = {
            1: """Ejemplo de reseña muy negativa:
"Terrible experiencia en este pueblo. Llegamos con muchas expectativas pero fue una gran decepción. Los restaurantes tienen precios altísimos y la comida es de mala calidad, fría y sin sabor. El personal fue grosero y desatento, tardaron más de una hora en servirnos. Las calles están sucias y descuidadas. Definitivamente no lo recomiendo, hay mejores opciones en la región."
""",
            2: """Ejemplo de reseña negativa:
"No cumplió nuestras expectativas. El lugar tiene potencial pero está muy descuidado. Los precios son elevados para lo que ofrecen. La atención del personal fue regular, nada especial. Esperábamos más por el costo. Hay varios aspectos que necesitan mejorar antes de que pueda recomendarlo a otros visitantes."
""",
            3: """Ejemplo de reseña neutral:
"Es un lugar normal, nada extraordinario. Tiene cosas buenas como la ubicación céntrica y algunos restaurantes decentes, pero también aspectos mejorables como el servicio que es lento. Los precios son justos, ni caros ni baratos. Si estás por la zona puedes visitarlo, pero no es un destino imprescindible."
""",
            4: """Ejemplo de reseña positiva:
"Muy buena experiencia en general. El pueblo es bonito y tiene un ambiente agradable. La atención del personal fue amable y servicial. La comida estuvo rica, especialmente los platillos típicos de la región. Los precios son razonables. Algunos detalles menores por mejorar, pero definitivamente lo recomiendo para una visita de fin de semana."
""",
            5: """Ejemplo de reseña muy positiva:
"¡Experiencia increíble! Este pueblo mágico superó todas nuestras expectativas. La comida es deliciosa, probamos varios restaurantes y todos excelentes. El ambiente es mágico, la arquitectura colonial hermosa. La gente es muy amable y hospitalaria. Los paisajes son espectaculares, perfectos para fotos. Vale totalmente la pena el viaje. Sin duda regresaríamos y lo recomendamos al cien por ciento."
"""
        }

        # Prompt mejorado con instrucciones más específicas
        prompt = f"""Eres un turista mexicano real escribiendo una reseña detallada sobre tu visita a {town}.

CONTEXTO DE TU VISITA:
- Lugar visitado: {town}
- Aspecto principal a comentar: {aspect}
- Tu experiencia fue: {self.POLARITY_PROMPTS[polarity]}

{ejemplos[polarity]}

INSTRUCCIONES PARA TU RESEÑA:
1. Escribe MÍNIMO 3 oraciones completas (entre {min_length} y {max_length} caracteres)
2. Primera oración: Da tu impresión general del lugar
3. Segunda oración: Comenta específicamente sobre "{aspect}"
4. Tercera oración: Añade detalles adicionales o tu recomendación final
5. Usa lenguaje natural mexicano (puedes usar: padre, chido, vale la pena, etc.)
6. Sé específico con detalles concretos y descriptivos
7. NO escribas solo una frase corta
8. NO incluyas etiquetas, números de calificación ni metadatos
9. Escribe como lo haría un turista real en TripAdvisor o Google Reviews

IMPORTANTE: Tu reseña debe tener AL MENOS 3 oraciones completas con detalles específicos.

Escribe tu reseña completa sobre {town} aquí:"""

        return prompt

    def generate_review(
        self,
        polarity: int,
        aspect: Optional[str] = None,
        town: Optional[str] = None,
        temperature: float = 0.85
    ) -> Optional[Dict]:
        """Genera una sola reseña sintética con validación."""

        aspect = aspect or random.choice(self.ASPECTS)
        town = town or random.choice(self.TOWNS)

        # Obtener características de estilo si están disponibles
        try:
            style_features = self.analyzer.extract_style_features(n_samples=50)
        except:
            style_features = {'avg_length': 100, 'top_words': []}

        # Construir prompt
        prompt = self._build_prompt(polarity, aspect, town, style_features)

        # Generar con Ollama - parámetros ajustados para respuestas más largas
        text = self.ollama.generate(
            prompt, 
            temperature=temperature, 
            max_tokens=350,  # Aumentado significativamente
            min_length=20  # Mínimo aceptable
        )

        if not text:
            return None

        # Validaciones post-generación
        text = text.strip()

        # Remover posibles artefactos del prompt y respuestas del modelo
        artifacts = [
            'Reseña:', 'Assistant:', '<|eot_id|>', '<|start_header_id|>',
            'Tu reseña sobre', 'Mi reseña:', 'Opinión:', 'Comentario:',
            f'sobre {town}:', f'{town}:', 'Aquí está', 'Aquí va',
            'La reseña es:', 'Escribo:', 'Mi opinión es:',
            'Escribe tu reseña', 'aquí:', 'completa sobre'
        ]
        for artifact in artifacts:
            text = text.replace(artifact, '').strip()
        
        # Limpiar comillas al inicio y final si las hay
        text = text.strip('"\'')
        
        # Limpiar saltos de línea múltiples
        text = ' '.join(text.split())

        # Validar longitud mínima
        if len(text) < RESTMEX_CONFIG['MIN_REVIEW_LENGTH']:
            logger.warning(f"⚠️ Reseña muy corta ({len(text)} chars): '{text[:50]}...'")
            return None

        # Validar que tenga al menos 2 oraciones (heurística: buscar puntos)
        sentence_count = text.count('.') + text.count('!') + text.count('?')
        if sentence_count < 1:
            logger.warning(f"⚠️ Reseña sin estructura de oraciones: '{text[:50]}...'")
            return None

        # Validar que no sea solo una palabra
        word_count = len(text.split())
        if word_count < 10:
            logger.warning(f"⚠️ Reseña con muy pocas palabras ({word_count}): '{text}'")
            return None

        if len(text) > RESTMEX_CONFIG['MAX_REVIEW_LENGTH']:
            text = text[:RESTMEX_CONFIG['MAX_REVIEW_LENGTH']].rsplit(' ', 1)[0] + "..."

        # Validar que esté en español (heurística simple)
        spanish_indicators = ['el', 'la', 'de', 'que', 'y', 'a', 'en', 'un', 'es', 'se', 'los', 'las']
        text_lower = text.lower()
        spanish_count = sum(1 for ind in spanish_indicators if ind in text_lower)
        if spanish_count < 2:
            logger.warning(f"⚠️ Posible reseña no en español: '{text[:50]}...'")
            return None

        return {
            'opinion': text,
            'polarity': polarity,
            'source': f"Ollama-{self.ollama.model}",
            'metadata': {
                'aspect': aspect,
                'town': town,
                'length': len(text),
                'timestamp': datetime.now().isoformat()
            }
        }

    def generate_corpus(self, balance_classes: bool = True) -> pd.DataFrame:
        """
        Genera el corpus completo de 3,000 reseñas sintéticas.

        Args:
            balance_classes: Si True, genera igual número por cada polaridad
                           (recomendado para métrica RP que premia clases minoritarias)
        """
        logger.info(f"🚀 Iniciando generación de {RESTMEX_CONFIG['TARGET_REVIEWS']} reseñas...")

        self.generated_reviews = []

        if balance_classes:
            # Generación balanceada: 600 por cada polaridad (1-5)
            polarities_to_generate = []
            for p in RESTMEX_CONFIG['POLARITY_CLASSES']:
                polarities_to_generate.extend([p] * self.target_per_class)
            random.shuffle(polarities_to_generate)
        else:
            # Generación con distribución similar a datos reales
            polarities_to_generate = []
            for p, info in self.analyzer.distribution.items():
                count = int(info['percentage'] / 100 * RESTMEX_CONFIG['TARGET_REVIEWS'])
                polarities_to_generate.extend([p] * count)
            # Ajustar para llegar exactamente a 3,000
            while len(polarities_to_generate) < RESTMEX_CONFIG['TARGET_REVIEWS']:
                polarities_to_generate.append(random.choice(RESTMEX_CONFIG['POLARITY_CLASSES']))
            polarities_to_generate = polarities_to_generate[:RESTMEX_CONFIG['TARGET_REVIEWS']]
            random.shuffle(polarities_to_generate)

        # Generación con barra de progreso
        for i, polarity in enumerate(tqdm(polarities_to_generate, desc="Generando reseñas")):
            review = self.generate_review(polarity)

            if review:
                self.generated_reviews.append(review)
                self.generation_log.append({
                    'index': i,
                    'polarity': polarity,
                    'success': True,
                    'length': len(review['opinion'])
                })
            else:
                self.generation_log.append({
                    'index': i,
                    'polarity': polarity,
                    'success': False
                })

            # Pequeña pausa para no saturar Ollama
            time.sleep(0.05)

            # Guardar checkpoint cada 500 reseñas
            if (i + 1) % 500 == 0:
                self._save_checkpoint(i + 1)

        # Crear DataFrame final
        df_result = pd.DataFrame([
            {k: v for k, v in r.items() if k != 'metadata'}
            for r in self.generated_reviews
        ])

        logger.info(f"✅ Generación completada: {len(df_result)} reseñas válidas")

        return df_result

    def _save_checkpoint(self, count: int):
        """Guarda un checkpoint intermedio de la generación."""
        if not self.generated_reviews:
            return

        checkpoint = pd.DataFrame([
            {k: v for k, v in r.items() if k != 'metadata'}
            for r in self.generated_reviews
        ])
        checkpoint_file = f"checkpoint_{count}_reviews.csv"
        checkpoint.to_csv(checkpoint_file, index=False, encoding='utf-8-sig')
        logger.info(f"💾 Checkpoint guardado: {checkpoint_file} ({count} reseñas)")

    def filter_duplicates(
        self,
        df: pd.DataFrame,
        threshold: float = RESTMEX_CONFIG['SIMILARITY_THRESHOLD']
    ) -> pd.DataFrame:
        """
        Filtra reseñas duplicadas semánticamente usando embeddings.
        """
        if len(df) == 0:
            return df

        logger.info(f"🔍 Filtrando duplicados semánticos (threshold={threshold})...")

        # Calcular embeddings
        embeddings = self.analyzer.compute_embeddings(df['opinion'].tolist())

        # Algoritmo greedy para seleccionar textos diversos
        selected_indices = []

        for i in tqdm(range(len(embeddings)), desc="Filtrando diversidad"):
            is_unique = True

            for j in selected_indices:
                # Similitud coseno
                sim = np.dot(embeddings[i], embeddings[j]) / (
                    np.linalg.norm(embeddings[i]) * np.linalg.norm(embeddings[j])
                )

                if sim > threshold:
                    is_unique = False
                    break

            if is_unique:
                selected_indices.append(i)

        df_filtered = df.iloc[selected_indices].reset_index(drop=True)

        removed = len(df) - len(df_filtered)
        logger.info(f"✅ Filtrado completado: {removed} duplicados removidos, "
                   f"{len(df_filtered)} reseñas únicas")

        return df_filtered

    def optimize_for_rp_metric(
        self,
        df_candidates: pd.DataFrame,
        df_real_val: pd.DataFrame,
        target_size: int = RESTMEX_CONFIG['TARGET_REVIEWS']
    ) -> pd.DataFrame:
        """
        Selecciona el subconjunto óptimo de reseñas para maximizar la métrica RP.
        Usa un clasificador proxy para evaluar la utilidad de los datos sintéticos.
        """
        logger.info("🎯 Optimizando subconjunto para métrica RP...")

        if len(df_candidates) <= target_size:
            # Si ya tenemos 3,000 o menos, asegurar balance y retornar
            return self._balance_and_sample(df_candidates, target_size)

        # Embeddings para entrenamiento proxy
        X_syn = self.analyzer.compute_embeddings(df_candidates['opinion'].tolist())
        y_syn = df_candidates['polarity'].values

        X_val = self.analyzer.compute_embeddings(df_real_val['review'].tolist())
        y_val = df_real_val['polarity'].values

        # Estrategia: selección iterativa greedy
        # (Simplificada para tiempo de ejecución - en producción usar Active Learning)

        # Paso 1: Entrenar clasificador base con todos los candidatos
        clf_base = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
        clf_base.fit(X_syn, y_syn)

        # Paso 2: Evaluar importancia de instancias (simplificado: muestreo estratificado)
        # Para cada polaridad, seleccionar las reseñas más "informativas"
        # (aquí usamos diversidad como proxy de informatividad)

        selected = []

        for polarity in RESTMEX_CONFIG['POLARITY_CLASSES']:
            mask = df_candidates['polarity'] == polarity
            df_class = df_candidates[mask].copy()

            if len(df_class) == 0:
                continue

            # Calcular embeddings de esta clase
            emb_class = self.analyzer.compute_embeddings(df_class['opinion'].tolist())

            # Seleccionar centroides (k-means simplificado)
            n_select = target_size // 5  # 600 por clase

            if len(df_class) <= n_select:
                selected.extend(df_class.index.tolist())
            else:
                # Selección por diversidad: elegir puntos lejanos entre sí
                selected_idx = [0]  # Empezar con el primero

                while len(selected_idx) < n_select and len(selected_idx) < len(df_class):
                    # Encontrar el punto más lejano a los ya seleccionados
                    max_min_dist = -1
                    best_idx = None

                    for i in range(len(df_class)):
                        if i in selected_idx:
                            continue

                        # Distancia mínima a cualquier punto ya seleccionado
                        min_dist = min(
                            1 - np.dot(emb_class[i], emb_class[j]) / (
                                np.linalg.norm(emb_class[i]) * np.linalg.norm(emb_class[j]) + 1e-8
                            )
                            for j in selected_idx
                        )

                        if min_dist > max_min_dist:
                            max_min_dist = min_dist
                            best_idx = i

                    if best_idx is not None:
                        selected_idx.append(best_idx)

                # Mapear índices locales a índices originales del DataFrame
                original_indices = df_class.index[selected_idx].tolist()
                selected.extend(original_indices)

        # Crear DataFrame final
        df_optimized = df_candidates.loc[selected].reset_index(drop=True)

        # Ajustar tamaño exacto si es necesario
        if len(df_optimized) > target_size:
            df_optimized = df_optimized.sample(n=target_size, random_state=42)

        logger.info(f"✅ Optimización completada: {len(df_optimized)} reseñas seleccionadas")

        return df_optimized

    def _balance_and_sample(self, df: pd.DataFrame, target_size: int) -> pd.DataFrame:
        """Asegura balance de clases y muestrea al tamaño objetivo."""
        if len(df) <= target_size:
            return df

        # Muestreo estratificado para mantener balance
        return df.groupby('polarity', group_keys=False).apply(
            lambda x: x.sample(n=min(len(x), target_size // 5), random_state=42)
        ).reset_index(drop=True)


# ============================================================================
# EVALUACIÓN Y VALIDACIÓN
# ============================================================================

class Evaluator:
    """
    Evalúa la calidad del corpus sintético usando la estrategia indirecta de REST-MEX.
    """

    def __init__(self, embedding_model: SentenceTransformer):
        self.embedding_model = embedding_model

    def compute_rp_metric(self, y_true: np.ndarray, y_pred: np.ndarray) -> float:
        """
        Calcula la métrica RP (ponderación de F1 para clases minoritarias).
        Inspirado en la descripción oficial de REST-MEX 2026.
        """
        # F1 por clase
        f1_per_class = f1_score(y_true, y_pred, average=None, labels=[1,2,3,4,5])

        # Pesos inversos a frecuencia típica en turismo (más peso a clases raras)
        # Basado en que reseñas negativas son minoritarias pero importantes
        weights = {1: 0.25, 2: 0.25, 3: 0.20, 4: 0.15, 5: 0.15}

        # F1 ponderado
        weighted_f1 = sum(
            f1_per_class[i] * weights[i+1]
            for i in range(5)
            if not np.isnan(f1_per_class[i])
        )

        return weighted_f1

    def evaluate_synthetic_corpus(
        self,
        df_synthetic: pd.DataFrame,
        df_real_val: pd.DataFrame,
        classifier_type: str = 'logistic'
    ) -> Dict:
        """
        Evalúa el corpus sintético entrenando un clasificador y probando en datos reales.
        """
        logger.info("🔬 Evaluando corpus sintético con estrategia indirecta...")

        # Preparar datos sintéticos para entrenamiento
        X_syn = self.embedding_model.encode(df_synthetic['opinion'].tolist())
        y_syn = df_synthetic['polarity'].values

        # Preparar datos reales para validación
        X_val = self.embedding_model.encode(df_real_val['review'].tolist())
        y_val = df_real_val['polarity'].values

        # Entrenar clasificador
        if classifier_type == 'logistic':
            clf = LogisticRegression(
                max_iter=1000,
                class_weight='balanced',
                random_state=42,
                C=1.0
            )
        else:
            raise ValueError(f"Clasificador no soportado: {classifier_type}")

        clf.fit(X_syn, y_syn)

        # Predecir en validación real
        y_pred = clf.predict(X_val)

        # Calcular métricas
        rp_score = self.compute_rp_metric(y_val, y_pred)
        macro_f1 = f1_score(y_val, y_pred, average='macro')

        # Reporte detallado por clase
        report = classification_report(
            y_val, y_pred,
            labels=[1,2,3,4,5],
            target_names=[RESTMEX_CONFIG['POLARITY_LABELS'][p] for p in [1,2,3,4,5]],
            output_dict=True
        )

        results = {
            'rp_score': round(rp_score, 4),
            'macro_f1': round(macro_f1, 4),
            'accuracy': round((y_pred == y_val).mean(), 4),
            'per_class_f1': {
                p: round(report[str(p)]['f1-score'], 4)
                for p in [1,2,3,4,5] if str(p) in report
            },
            'confusion_summary': {
                'total_val': len(y_val),
                'correct_predictions': int((y_pred == y_val).sum())
            }
        }

        logger.info("📊 Resultados de evaluación:")
        logger.info(f"  • RP Score (métrica oficial): {results['rp_score']:.4f}")
        logger.info(f"  • Macro F1: {results['macro_f1']:.4f}")
        logger.info(f"  • Accuracy: {results['accuracy']:.4f}")
        logger.info(f"  • F1 por clase: {results['per_class_f1']}")

        return results


# ============================================================================
# EXPORTACIÓN Y VALIDACIÓN FINAL
# ============================================================================

def validate_submission(df: pd.DataFrame) -> List[str]:
    """
    Valida que el DataFrame cumpla con todos los requisitos de REST-MEX 2026.
    Retorna lista de errores (vacía si todo está bien).
    """
    errors = []

    # 1. Verificar columnas requeridas
    for col in RESTMEX_CONFIG['REQUIRED_COLUMNS'][:2]:  # opinion, polarity (source es opcional según ejemplo)
        if col not in df.columns:
            errors.append(f"❌ Columna faltante: '{col}'")

    if errors:
        return errors

    # 2. Verificar número de filas
    if len(df) > RESTMEX_CONFIG['TARGET_REVIEWS']:
        errors.append(f"❌ Demasiadas filas: {len(df)} > {RESTMEX_CONFIG['TARGET_REVIEWS']}")

    if len(df) == 0:
        errors.append("❌ DataFrame vacío")
        return errors

    # 3. Verificar valores nulos
    if df[['opinion', 'polarity']].isnull().any().any():
        errors.append("❌ Valores nulos en columnas requeridas")

    # 4. Verificar polaridades válidas
    invalid_polarities = df[~df['polarity'].isin(RESTMEX_CONFIG['POLARITY_CLASSES'])]
    if len(invalid_polarities) > 0:
        errors.append(f"❌ Polaridades inválidas encontradas: {invalid_polarities['polarity'].unique().tolist()}")

    # 5. Verificar longitud de reseñas
    short_reviews = df[df['opinion'].str.len() < RESTMEX_CONFIG['MIN_REVIEW_LENGTH']]
    if len(short_reviews) > 0:
        errors.append(f"⚠️ {len(short_reviews)} reseñas muy cortas (< {RESTMEX_CONFIG['MIN_REVIEW_LENGTH']} chars)")

    # 6. Verificar que sean strings
    if df['opinion'].dtype != 'object' or not all(isinstance(x, str) for x in df['opinion']):
        errors.append("❌ Columna 'opinion' debe contener strings")

    # 7. Verificar que polarity sea entero
    if not pd.api.types.is_integer_dtype(df['polarity']):
        errors.append("❌ Columna 'polarity' debe contener enteros")

    # 8. Verificar idioma (heurística: presencia de palabras en español)
    spanish_words = ['el', 'la', 'de', 'que', 'y', 'en', 'un', 'es', 'se', 'muy', 'bueno', 'mal']
    non_spanish = []

    for i, text in enumerate(df['opinion'].head(100)):  # Muestrear 100 para eficiencia
        text_lower = text.lower()
        if not any(word in text_lower for word in spanish_words):
            non_spanish.append(i)

    if len(non_spanish) > 20:  # Permitir algunos falsos positivos
        errors.append(f"⚠️ Posibles reseñas no en español: {len(non_spanish)} de 100 muestreadas")

    return errors


def export_submission(
    df: pd.DataFrame,
    output_path: str,
    team_name: str = "PhD_Team"
) -> str:
    """
    Exporta el DataFrame final en el formato exacto requerido por REST-MEX 2026.
    """
    # Crear copia para no modificar el original
    df_export = df.copy()

    # Asegurar columnas en orden correcto (según ejemplo del reto)
    columns_order = ['opinion', 'polarity']
    if 'source' in df_export.columns:
        columns_order.append('source')

    df_export = df_export[columns_order]

    # Asegurar tipos de dato correctos
    df_export['polarity'] = df_export['polarity'].astype(int)
    df_export['opinion'] = df_export['opinion'].astype(str)

    # Si falta 'source', agregar valor por defecto
    if 'source' not in df_export.columns:
        df_export['source'] = f"Ollama-llama3-{team_name}"

    # Validación final antes de exportar
    errors = validate_submission(df_export)
    if errors:
        logger.warning("⚠️ Advertencias de validación antes de exportar:")
        for error in errors:
            logger.warning(f"  {error}")

    # Exportar CSV con encoding UTF-8-SIG para compatibilidad con Excel
    df_export.to_csv(output_path, index=False, encoding='utf-8-sig')

    logger.info(f"✅ Archivo de envío generado: {output_path}")
    logger.info(f"📊 Estadísticas del envío:")
    logger.info(f"  • Total reseñas: {len(df_export)}")
    logger.info(f"  • Columnas: {df_export.columns.tolist()}")
    logger.info(f"  • Distribución de polaridades:")

    for p in RESTMEX_CONFIG['POLARITY_CLASSES']:
        count = (df_export['polarity'] == p).sum()
        logger.info(f"    {p} ({RESTMEX_CONFIG['POLARITY_LABELS'][p]}): {count}")

    return output_path


# ============================================================================
# FUNCIÓN PRINCIPAL
# ============================================================================

def main():
    """Función principal del script."""

    # Parsear argumentos de línea de comandos
    parser = argparse.ArgumentParser(
        description='REST-MEX 2026: Generador de reseñas sintéticas con Ollama',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument('--input', '-i', required=True,
                       help='Ruta al CSV con datos reales de entrenamiento')
    parser.add_argument('--output', '-o', default='submission_restmex_2026.csv',
                       help='Ruta para el archivo de envío final')
    parser.add_argument('--ollama-url', '-u', default=None,
                       help='URL base de Ollama API (por defecto: http://localhost:11434 para local)')
    parser.add_argument('--ollama-key', '-k', default=None,
                       help='API Key para Ollama (si requiere autenticación)')
    parser.add_argument('--model', '-m', default='llama3',
                       help='Nombre del modelo en Ollama')
    parser.add_argument('--mode', choices=['local', 'web'], default='local',
                       help='Modo de conexión a Ollama: local (localhost) o web (servidor remoto)')
    parser.add_argument('--team', '-t', default='PhD_Team',
                       help='Nombre del equipo para el campo "source"')
    parser.add_argument('--no-balance', action='store_true',
                       help='No balancear clases (usar distribución real)')
    parser.add_argument('--skip-eval', action='store_true',
                       help='Saltar evaluación con clasificador proxy')
    parser.add_argument('--val-split', type=float, default=0.2,
                       help='Proporción de datos reales para validación')

    args = parser.parse_args()

    # ========================================================================
    # PASO 1: Cargar y analizar datos reales
    # ========================================================================
    logger.info("=" * 70)
    logger.info("REST-MEX 2026: Iniciando pipeline de generación sintética")
    logger.info("=" * 70)

    try:
        analyzer = DataAnalyzer()
        df_real = analyzer.load_data(args.input)
        distribution = analyzer.analyze_distribution()
        style_features = analyzer.extract_style_features()

    except Exception as e:
        logger.error(f"❌ Error cargando datos: {e}")
        sys.exit(1)

    # Dividir datos reales para validación (hold-out)
    if not args.skip_eval and len(df_real) >= 50:
        df_real_train, df_real_val = train_test_split(
            df_real,
            test_size=args.val_split,
            stratify=df_real['polarity'],
            random_state=42
        )
        logger.info(f"📊 Datos para análisis: {len(df_real_train)}, validación: {len(df_real_val)}")
    else:
        df_real_val = None
        logger.info("⚠️ Evaluación omitida o datos insuficientes para validación")

    # ========================================================================
    # PASO 2: Inicializar cliente Ollama
    # ========================================================================
    logger.info(f"\n🔗 Conectando a Ollama ({args.mode}): {args.model}")

    ollama_url = args.ollama_url
    if not ollama_url:
        if args.mode == 'local':
            ollama_url = "http://localhost:11434"
        else:
            # Para modo web, el usuario debe proporcionar la URL
            ollama_url = os.getenv("OLLAMA_API_URL", "http://localhost:11434")

    try:
        with OllamaClient(
            model=args.model,
            base_url=ollama_url,
            api_key=args.ollama_key,
            mode=args.mode
        ) as ollama:

            # Verificar conexión
            if not ollama.test_connection():
                logger.error("❌ No se pudo conectar a Ollama. Verifica que esté corriendo.")
                logger.info("💡 Comandos útiles:")
                logger.info("   • Local:   ollama serve")
                logger.info("   • Modelos: ollama pull llama3")
                sys.exit(1)

            # ====================================================================
            # PASO 3: Generar corpus sintético
            # ====================================================================
            generator = SyntheticReviewGenerator(
                ollama_client=ollama,
                data_analyzer=analyzer,
                target_per_class=600  # 600 × 5 = 3,000
            )

            # Generar con posible sobregeneración para filtrado posterior
            df_raw = generator.generate_corpus(balance_classes=not args.no_balance)

            # Filtrar duplicados semánticos
            df_filtered = generator.filter_duplicates(df_raw)

            # ====================================================================
            # PASO 4: Optimizar para métrica RP (si hay datos de validación)
            # ====================================================================
            if not args.skip_eval and df_real_val is not None and len(df_real_val) >= 20:
                df_optimized = generator.optimize_for_rp_metric(
                    df_filtered,
                    df_real_val,
                    target_size=RESTMEX_CONFIG['TARGET_REVIEWS']
                )
            else:
                # Si no hay validación, simplemente muestrear a 3,000
                if len(df_filtered) > RESTMEX_CONFIG['TARGET_REVIEWS']:
                    df_optimized = df_filtered.sample(
                        n=RESTMEX_CONFIG['TARGET_REVIEWS'],
                        random_state=42
                    ).reset_index(drop=True)
                else:
                    df_optimized = df_filtered.reset_index(drop=True)

            # ====================================================================
            # PASO 5: Evaluación con clasificador proxy
            # ====================================================================
            if not args.skip_eval and df_real_val is not None:
                evaluator = Evaluator(analyzer.embedding_model)
                eval_results = evaluator.evaluate_synthetic_corpus(
                    df_optimized,
                    df_real_val
                )

                # Guardar resultados de evaluación
                eval_path = f"evaluation_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
                with open(eval_path, 'w', encoding='utf-8') as f:
                    json.dump(eval_results, f, indent=2, ensure_ascii=False)
                logger.info(f"📄 Resultados de evaluación guardados: {eval_path}")

            # ====================================================================
            # PASO 6: Exportar archivo de envío
            # ====================================================================
            final_path = export_submission(df_optimized, args.output, args.team)

            # ====================================================================
            # PASO 7: Resumen final
            # ====================================================================
            logger.info("\n" + "=" * 70)
            logger.info("✅ PIPELINE COMPLETADO EXITOSAMENTE")
            logger.info("=" * 70)
            logger.info(f"📦 Archivo de envío: {final_path}")
            logger.info(f"📊 Reseñas generadas: {len(df_optimized)}")
            logger.info(f"🏷️  Equipo: {args.team}")
            logger.info(f"🦙 Modelo: {args.model} ({args.mode})")
            logger.info("\n📋 Checklist antes de enviar:")
            logger.info("  □ Verificar que el CSV tenga columnas: opinion, polarity, source")
            logger.info("  □ Confirmar que polarity son enteros 1-5")
            logger.info("  □ Asegurar que no hay celdas vacías")
            logger.info("  □ Enviar a: miguel.alvarez@cimat.mx")
            logger.info("  □ Fecha límite: April 24, 2026 (23:59 UTC-06:00)")
            logger.info("=" * 70)

    except KeyboardInterrupt:
        logger.warning("\n⚠️ Ejecución interrumpida por el usuario")
        sys.exit(130)
    except Exception as e:
        logger.error(f"\n❌ Error fatal en el pipeline: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()